In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a = [2,3,4,5,6]
a

[2, 3, 4, 5, 6]

In [13]:
l = [[1,2,3],[4,5,5],[6,7,8]]
l

[[1, 2, 3], [4, 5, 5], [6, 7, 8]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8]])

In [16]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [30]:
arr = np.random.rand(10)
arr

array([0.48091237, 0.49617236, 0.9581476 , 0.34934403, 0.55726388,
       0.76193982, 0.09412063, 0.85739622, 0.4415164 , 0.51567997])

In [32]:
arr = np.random.randn(10)
arr

array([-2.41684184, -0.18427182, -0.28250721,  0.13529408, -0.90064901,
       -0.41234411,  0.52981215,  0.56831133,  0.54896138,  0.15228225,
        0.82017005, -1.11689651,  0.80224283, -1.13938544,  0.57901694,
       -0.0567031 ,  1.31095844, -0.6097368 ,  1.47398552,  0.89529405])

In [36]:
arr = np.random.randint(10, 20, 10)
arr

array([16, 19, 13, 19, 18, 18, 10, 10, 15, 15])

In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.shape # find out the shap of martix

(3, 3)

In [44]:
arr.size

9

In [45]:
arr.dtype

dtype('int32')

In [46]:
#Array Methods

In [47]:
arr.min() #minimum element in an array

1

In [48]:
arr.max() # maximum element in an array

9

In [50]:
arr.sum() # sum of all the elements that persent in an array

45

In [53]:
np.sum(arr, axis = 1) # axis = 1 meas row wise sum and 0 means col wise sum

array([ 6, 15, 24])

In [54]:
arr.mean()

5.0

In [55]:
arr.std()

2.581988897471611

In [56]:
arr.argmax()

8

In [57]:
arr.argmin()

0

In [58]:
# Reshaping and Resizing 

In [60]:
 arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [61]:
arr.reshape(6, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [2]:
import numpy as np

In [6]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[:4]

array([11, 12, 13, 14])

In [ ]:
# NUMPY INDEXING AND SLICINGOF MATRIX

In [9]:
arr = np.arange(1, 31).reshape(6, 5) #WHERE ROW = 6, COL = 5
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[5]

array([26, 27, 28, 29, 30])

In [14]:
arr[5,4] # if you try to access single element of matrix then you have to follow arr[a1, a1] <- like this

30

In [15]:
slc = arr[0:2, 1:3]
slc

array([[2, 3],
       [7, 8]])

In [19]:
slc = arr[3:, 3:]
slc

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
bool_index = arr%2 == 0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [ ]:
# Airthmatic Oprations

In [9]:
import numpy as np

In [13]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [14]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [15]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [16]:
a1 % a2

array([1, 2, 3, 4, 5])

In [17]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [18]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [19]:
a1 // a2

array([0, 0, 0, 0, 0])

In [20]:
a1 ** a2 # power

array([      1,     128,    6561,  262144, 9765625])

In [21]:
# Brodcasting

In [22]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [24]:
arr + 10

array([20, 30, 40, 50])

In [30]:
arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
# Deep and Shallow copy

In [33]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
a[4:6] * 10

array([50, 60])

In [40]:
a
b = a # shallow copy

In [41]:
b[0] = 99

In [42]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
a
b = a.copy() # Deep copy
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
# MATRIX OPRATIONS

In [50]:
A = np.array([[1,2], [4,5]])
B = np.array([[6,7], [8,9]])

A

In [53]:
B

array([[6, 7],
       [8, 9]])

In [55]:
A @ B

array([[22, 25],
       [64, 73]])

In [56]:
np.dot(A,B)

array([[22, 25],
       [64, 73]])

In [57]:
A.T # Transpose of matrix

array([[1, 4],
       [2, 5]])

In [58]:
(A @ B).T # Transpose of matrix

array([[22, 64],
       [25, 73]])

In [62]:
d = np.array([1,2,3,4])
c = np.array([6,7,8,9,])

In [65]:
np.vstack((d,c)) # Vertically stack

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [66]:
np.hstack((d,c)) # Horizonatallly Stack

array([1, 2, 3, 4, 6, 7, 8, 9])

In [68]:
np.column_stack((d,c)) # Column Stack

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [69]:
# Spliting an Array

In [71]:
e = np.arange(16).reshape(4,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.hsplit(e,2) # ONlY EQUAL DEVISION IS POSSIBLE

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [79]:
np.vsplit(e, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [81]:
for i in e:
    print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
