In [1]:
# Valid Sudoku

In [2]:
import numpy as np

In [23]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [25]:
a = np.sum(s, axis = 1)
for i in a:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for Row")

Sudoku is valid for Row


In [26]:
a = np.sum(s, axis = 0)
for i in a:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for Col")

Sudoku is valid for Col


In [27]:
s[0:3, 0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [33]:
for i in range(0, 9, 3): 
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [29]:
s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [34]:
# GENERAL QUESTIONS

In [36]:
import numpy as np
# cloumn: [Age, OOPs, CN]
data = np.array([
    [12, 13, 14],
    [14, 15, 16],
    [16, 17, 18],
    [18, 19, 20],
    [20, 21, 22]
])

In [38]:
data.shape

(5, 3)

In [39]:
np.mean(data[:,0])

16.0

In [41]:
data[:,1]

array([13, 15, 17, 19, 21])

In [43]:
np.max(data[:, 2])

22

In [46]:
data[data[:, 1] > 20]

array([[20, 21, 22]])

In [47]:
data[:,1] + 5

array([18, 20, 22, 24, 26])

In [48]:
data

array([[12, 13, 14],
       [14, 15, 16],
       [16, 17, 18],
       [18, 19, 20],
       [20, 21, 22]])

In [51]:
age = data[:,0] < 18
age

array([ True,  True,  True, False, False])

In [52]:
len(data[:,0] < 18)

5

In [54]:
np.mean(data[:,1:], axis = 0)

array([17., 18.])

In [56]:
data[(data[:,1] >= 20) & (data[:,2] >= 20)]

array([[20, 21, 22]])

In [57]:
data

array([[12, 13, 14],
       [14, 15, 16],
       [16, 17, 18],
       [18, 19, 20],
       [20, 21, 22]])

In [71]:
data[:,2][data[:,2] < 20] = 0
data


array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [18, 19,  0],
       [20, 21,  0]])